### ISSUE TITLE
Focus gets stuck after editing a phrase and opening a new Chrome window with Command+N

### ISSUE THREAD

**Issue by AbrahamCain** [Drentem/LOPFIT#53]
Using Google Chrome, if you go in click on a phrase in the LOPFIT tab, and then use Command+N to open a new window, this seems to get the focus stuck in the LOPFIT window so that no phrases can be picked up or executed even if clicking into the LOPFIT window and clicking back into anything else like Atom or another tab in Chrome. 

This issue persists even after closing the LOPFIT tab or changing to a different tab in that window.

**Comment by Drentem** [comment]
So, the loss of focus is not being caught by JS? Interesting.

**Comment by Drentem** [comment]
I ran into this issue before.... It isn't a loss of focus issue. It's stranger than that. It's almost like it doesn't want to resume. Closing and re-opening it brings everything back. I'll have to debug this further.

**Comment by Drentem** [comment]
Looks like how I was handling a "pause" in the event cycle failed to work. (don't use variables as flags across threads lol)

Switched to an event flag. Seems to work better.

**Comment by Drentem** [comment]
@AbrahamCain Let me know if that corrected the issue for you

**Comment by Drentem** [comment]
After direct discussion, this has been fixed.
